---
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: initialize postgres
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
- name: start and enable postgres
  service:
    name: postgresql
    state: started
    enabled: true
